### ISSUE TITLE
Won't work, what to do next?

### ISSUE THREAD

**Issue by FrankyXie** [Pzoom522/SiCM#2]
你好，我能请问一下怎么样运行这个python项目么
我以及下载到本地了，也应该import 了需要的插件。
就是不知道要怎么跑起来这个。
谢谢了

**Comment by Pzoom522** [comment]
请问你配(gou)置(mai)AWS的队列服务了吗？如果想不修改代码直接跑起来，需要把你的key填写进去。以及，你是想放在网页上（就是在cgi环境）还是想在本地命令行运行？

**Comment by FrankyXie** [comment]
你好 我想在本地运行 目前没有购买AWS的服务
谢谢

**Comment by Pzoom522** [comment]
@FrankyXie 那么你只需要comments.py一个文件，但是需要自己屏蔽掉与AWS队列相关的操作。我目前没有时间进行这个工作，但是本身不难。当时选择aws.sqs是为了保护队列稳定性，去除后对功能没有影响

**Comment by FrankyXie** [comment]
知道了！
谢谢耐心的帮助。：)

**Comment by Pzoom522** [comment]
没事
